name: Update versions

on: [push]

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[build]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Pull changes
      run: |
        git pull origin master
    - name: Update versions
      run: |
        npm start
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Page Builder"
        git add -f *
        git commit -m "Update version"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}